
FROM 246618743249.dkr.ecr.us-west-2.amazonaws.com/sagemaker-scikit-learn:1.2-1-cpu-py3

RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
RUN apt-get update
RUN apt-get install -y libgl1-mesa-glx
RUN apt-get install -y libglib2.0-0
RUN apt-get install -y poppler-utils

RUN pip install -U pip
RUN pip install botocore==1.39.10
RUN pip install boto3==1.39.9
RUN pip install sagemaker==2.248.1
RUN pip install langchain==0.3.26
RUN pip install langchain_aws==0.2.29
RUN pip install langchain_community==0.3.20
RUN pip install requests_toolbelt==1.0.0
RUN pip install pdf2image==1.17.0
RUN pip install numpy==1.26.4
RUN pip install ipython==8.18.1
RUN pip install opensearch-py==3.0.0
RUN pip install matplotlib==3.9.4
RUN pip install pillow>=10.0.0

ENV PYTHONUNBUFFERED=TRUE
